--
-- SCRIPT INICIAL DO BANCO DE DADOS
-- DATA: 22/02/2020
-- IVAN B. MORENO
--
-- SET search_path TO public;

-- CRIA TABELA EMPRESA
CREATE TABLE EMPRESA
(
    CODIGO          numeric     NOT NULL,
    NOME            varchar(75) NOT NULL,
    FANTASIA        varchar(75) NOT NULL,
    CNPJ            varchar(14) NOT NULL,
    DATA_ATUALIZADO timestamp without time zone NOT NULL,
    DATA_CADASTRADO timestamp without time zone NOT NULL
);

-- CRIA CHAVE PRIMARIA PARA FORNECEDOR_BANCO
ALTER TABLE ONLY EMPRESA
    ADD CONSTRAINT PK_EMPRESA PRIMARY KEY (CODIGO);

-- CRIA SEQUENCIA DE EMPRESA
CREATE SEQUENCE SEQ_EMPRESA
    START 1
    INCREMENT 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1;
